import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./_components/Footer/Footer";
import Navbar from "./_components/Navbar/Navbar";
import TopBar from "./_components/TopBar/TopBar";
import { Toaster } from "sonner";
import NextAuthContext from "_/api/services/context/WrapperForSessionProvider";
import CartContextProvider from "./_context/CartContext";
import { getUserCart } from "_/api/services/rout.services";
import { CartResponse } from "_/api/services/types";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FreshCart",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const res = await getUserCart();


  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body suppressHydrationWarning>
        <CartContextProvider res = {res}>
        <NextAuthContext>
        <TopBar />
        <Navbar />
          <Toaster position="top-right" />
          
            {children}
          
        <Footer />
        </NextAuthContext>
        </CartContextProvider>
      </body>
    </html>
  );
}
